---
collections:
  - name: community.docker
    version: ">=3.0.0"
  - name: community.general
    version: ">=5.0.0"
  - name: ansible.posix
    version: ">=1.4.0"

roles:
  - name: geerlingguy.docker
    version: ">=6.0.0"
  - name: geerlingguy.nginx
    version: ">=3.1.0"